version: '3.8'

services:
  postgres:
    image: postgres:13.1
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
      - RAILS_MASTER_KEY
    ports:
      - "3000:3000"
    command: sh -c "bundle exec rails db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"

volumes:
  postgres_data:
