version: '3.8'

services:
  postgres:
    image: postgres:13.1-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    image: redis:5-alpine
    command: redis-server
    volumes:
      - redis_data:/var/lib/redis/data

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq --environment ${RAILS_ENVIRONMENT}
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    volumes:
      - ./config/master.key:/app/config/master.key
    environment:
      - REDIS_URL

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - sidekiq
      - postgres
    env_file:
      - .env
    environment:
      - REDIS_URL
    ports:
      - 3000:3000
    volumes:
      - ./config/master.key:/app/config/master.key
    command:
      - /bin/sh
      - -c
      - |
        bundle exec rails db:create RAILS_ENV=${RAILS_ENVIRONMENT}
        bundle exec rails db:migrate RAILS_ENV=${RAILS_ENVIRONMENT}
        rm -f tmp/pids/server.pid
        bundle exec rails s -e ${RAILS_ENVIRONMENT} -p 3000 -b 0.0.0.0

volumes:
  redis_data:
  postgres_data:
