name: RSpec

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      POSTGRES_USER: chatgpt
      POSTGRES_PASSWORD: chatgpt
      POSTGRES_DB: chatgpt_test
      DATABASE_URL: postgres://chatgpt:chatgpt@localhost:5432/chatgpt_test
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: chatgpt
          POSTGRES_PASSWORD: chatgpt
          POSTGRES_DB: chatgpt_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Setup DB
        run: bundle exec rake db:setup
      - name: Run RSpec
        run: bundle exec rspec
